version: 2.1.{build}
image: Visual Studio 2017


environment:
  matrix:
    - PlatformToolset: v140_xp
    - PlatformToolset: v141_xp

platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug


install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - if "%PlatformToolset%"=="v140_xp" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="v141_xp" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%


build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild NppTaskList.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%" /p:PlatformToolset="%PlatformToolset%" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            #Push-AppveyorArtifact "bin\$env:PLATFORM_INPUT\NppTaskList.dll" -FileName NppTaskList.dll
        }

        if ($env:PLATFORM_INPUT -eq "Win32" -and $env:CONFIGURATION -eq "Release") {
            #Push-AppveyorArtifact "bin\$env:PLATFORM_INPUT\NppTaskList.dll" -FileName NppTaskList.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v140_xp") {
            if($env:PLATFORM_INPUT -eq "x64"){
                $ZipFileName = "NppTaskList_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
                7z a $ZipFileName .\bin\$env:PLATFORM_INPUT\NppTaskList.dll
                7z a $ZipFileName config\npp_task_list.cfg
            }
            if($env:PLATFORM_INPUT -eq "Win32"){
                $ZipFileName = "NppTaskList_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
                7z a $ZipFileName .\bin\$env:PLATFORM_INPUT\NppTaskList.dll
                7z a $ZipFileName config\npp_task_list.cfg
            }
        }

artifacts:
  - path: NppTaskList_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v140_xp
        configuration: Release
